version: '3'
services:
  db:
    container_name: mydb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: w8woord
      MYSQL_DATABASE: codetest
      MYSQL_USER: gebruiker
      MYSQL_PASSWORD: w8woord
    ports:
      - "3306:3306"
  app:
    container_name: myapp
    build: .
    volumes:
      - .:/app
    depends_on:
      - db